nyanya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nya.urls'))
]

urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view(template_name = 'login.html')),
    path('logout/', LogoutView.as_view(template_name='logout.html')),
    path('booking/', BookingView.as_view()),
    path('', DashboardView.as_view()),
    path('bookings/', Zayavki.as_view())
]

models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    full_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =  ['full_name', 'phone', 'username']

class Booking(models.Model):
    pm = {
        '1': 'наличные',
        '2': 'карта',
    }
    bs = {
        '1': 'в разработке',
        '2': 'отменено',
        '3': 'подтверждено',
    }
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    nyanya = models.ForeignKey('Nyanya', on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=20, choices=pm)
    booking_status = models.CharField(max_length=20, choices=bs)
    data = models.DateTimeField()
    cancel = models.TextField(blank=True)

class Nyanya(models.Model):
    detii = {
        '1': 'малыши',
        '2': 'школьники',
        '3': 'подростки',
    }
    name = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=20)
    age = models.IntegerField()
    deti = models.CharField(max_length=20, choices=detii)

    def __str__(self):
        return self.name
    


forms.py
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['full_name', 'phone', 'username', 'email', 'password1', 'password2']
        

class BookingForm(forms.ModelForm):
    data = forms.DateTimeField(widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}))
    class Meta:
        model = Booking
        fields = ['nyanya', 'payment_method', 'data']

views.py
from django.shortcuts import render
from .forms import *
from .models import User, Nyanya, Booking
from django.views.generic import CreateView, ListView

class RegisterView(CreateView):
    success_url = '/login/'
    form_class = RegisterForm
    template_name = 'register.html'

class BookingView(CreateView):
    success_url = '/'
    form_class = BookingForm
    template_name = 'booking.html'
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.booking_status = '1'
        return super().form_valid(form)
    
class DashboardView(ListView):
    model = Nyanya
    template_name = 'dashboard.html'

class Zayavki(ListView):
    model = Booking
    template_name = 'zayavki.html'
    def get_queryset(self):
        return Booking.objects.filter(user = self.request.user)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel = 'stylesheet' href = '{% static "pico/css/pico.min.css" %}'>
</head>
<body>
    <main class = 'container'>
    <nav>
        <ul>
        <li ><a href = '/login'> VHOD </a></li>
        <li ><a href = '/register'> REGISTER </a></li>
        <li><a href = '/booking'> BOOKING </a></li>
        <a href = '/bookings'> BOOKINGS </a>
        <a href = '/'> OSNOVNAYAA </a>
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}
    <main>
</body>
</html>

templates/booking.html
{% extends "base.html" %}
{% block content %}
<form action='/booking/' method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type = 'submit' value = 'booking'>
</form>
{% endblock content %}



templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div style = 'display: flex'>
{% for nyanya in object_list %}
<div style = "padding: 10px">
<h1>{{nyanya.name}}</h1>
<p> {{nyanya.phone}} </p>
<p> {{nyanya.age}} </p>
<p> {{nyanya.get_deti_display}} </p>
</div>
{% endfor %}
</div>
{% endblock content %}




templates/login.html
{% extends "base.html" %}
{% block content %}
<form action="/login/" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="login">
</form>
{% endblock content %}

templates/register.html
{% extends "base.html" %}
{% block content %}
<form action="/register/" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="register">
</form>
{% endblock content %}

templates/zayavki.html
{% extends "base.html" %}
{% block content %}
{% for booking in object_list %}
{{booking.nyanya}}
{{booking.get_booking_status_display}}
{{booking.data}}
{{booking.cancel}}
{% endfor %}
{% endblock content %}

